plugin_blacklist:
- 3dr_radio
- actuator_control
- adsb
- altitude
- cam_imu_sync
- command
- companion_process_status
- debug_value
- distance_sensor
- esc_status
- fake_gps
- ftp
- global_position
- gps_rtk
- gps_status
- hil
- home_position
#- imu
- landing_target
# - local_position
- log_transfer
- manual_control
- mocap_pose_estimate
- mount_control
- obstacle_distance
- odom
- onboard_computer_status
- param
- play_tune
- px4flow
- rangefinder
- rc_io
- safety_area
- setpoint_accel
- setpoint_attitude
- setpoint_position
- setpoint_raw
- setpoint_trajectory
- setpoint_velocity
- sys_status
- sys_time
- trajectory
- vfr_hud
- vibration
- vision_pose_estimate
- vision_speed_estimate
- waypoint
- wheel_odometry
- wind_estimation
#- whud_basic_control
#- whud_nav_control
#- whud_sensor_update

plugin_whitelist:
#- 'sys_*'
- imu
- local_position
- whud_basic_control
- whud_nav_control
- whud_sensor_update
